" Delete with dd instead of cutting
nnoremap dd "_dd
vnoremap dd "_d

" Connect keyboard to vim clipboard
set clipboard=unnamedplus

" Faster scrolling
nnoremap <C-Up> <C-u>
nnoremap <C-Down> <C-d>
nnoremap <C-Left> 5zh
nnoremap <C-Right> 5zl
